# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 14:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('buy_time', models.DateTimeField(auto_now_add=True)),
                ('responsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bianhao', models.CharField(max_length=50)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
                ('order_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('daihao', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Raw_material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daihao', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Product'),
        ),
    ]
